### ISSUE TITLE
[Sugerencia] Cambiar el modelo de los paracaídas

### ISSUE THREAD

**Issue by zarzanduil** [MultiTheFranky/41st-StarWars-Mod#2]
# Cambiar el modelo de los paracaidas
Estaría bastante curioso que se cambiara el modelo 3D de la mochila del paracaídas a una más acorde con la temática de Star Wars, como, por ejemplo en la imagen que muestro más abajo.

No es el mejor angulo pero es la única imagen que he encontrado en la que se ve explícitamente un paracaídas usado por un clon.

![imagen](https://user-images.githubusercontent.com/45758857/57636246-0c6e7880-75a9-11e9-8409-da43c87d33f2.png)
_Imagen de paracaidistas clones_

**Comment by spachesp** [comment]
como nota, añadir que lo mismo se podría cambiar la textura actual de dicho paracaídas por la textura de la mochila de salto, creo que quedaría bien y daría el pego, siempre y cuando fuera sencillo de hacer.

**Comment by MultiTheFranky** [comment]
Commited
