### ISSUE TITLE
[Bug] Crasheo al pilotar Laats.

### ISSUE THREAD

**Issue by spachesp** [MultiTheFranky/41st-StarWars-Mod#3]
**Describe the bug**
De manera complétamente random al estar pilotando el laat a los pilotos nos crashea el arma3 con el siguiente error:

 0xC0000409 - STATUS_STACK_BUFFER_OVERRUN

**To Reproduce**
No sabemos como reproducirlo, a veces puede ocurrir 3 veces por misión como pueden pasar 3 misiones sin que ocurra.

**Expected behavior**
Que no crashee :(

**Screenshots**

**Desktop (please complete the following information):**
 - Windows10
 - Chrome
 - npi que versión.

**Comment by MultiTheFranky** [comment]
Por favor añadir rpt de la sesión del crasheo y mas o menos el momento dentro de la sesión.

**Comment by spachesp** [comment]
ya te lo había mandado por el discord pero te lo pongo aquí otra vez.

**Comment by spachesp** [comment]
no dije nada franky, estoy empanado, me confundí con el otro post de github, esto es muy moderno para mí

**Comment by spachesp** [comment]
estuve mirando y no tengo el RPT, cuando nos vuelva a pasar te paso el archivo

**Comment by MultiTheFranky** [comment]
Not applied right now
