### ISSUE TITLE
[Bug] Cambio de contramedidas no autorizado

### ISSUE THREAD

**Issue by spachesp** [MultiTheFranky/41st-StarWars-Mod#4]
**Describe the bug**
Cuando se cuenta con un artillero jugador en el laat, a veces cuando este abre fuego causa que las contramedidas seleccionadas en el laat cambien a las que vienen por defecto al encender el laat, las cuales están bugueadas y no sirven para nada (nombre: countermeasures)

**To Reproduce**
Montarse en el laat un piloto y un copiloto
El copiloto al abrir fuego puede causar el cambio de las contramedidas.

**Expected behavior**
No cambiar las contramedidas

**Comment by MultiTheFranky** [comment]
Not applied right now
