### ISSUE TITLE
[Petición] Añadir diferentes modos de visión al casco personalizado de krayt

### ISSUE THREAD

**Issue by spachesp** [MultiTheFranky/41st-StarWars-Mod#5]
Los cascos estandar de piloto del swop/501 tienen 3 diferentes tipos de visión, nocturna, térmica, infraroja, al tener krayt unos cascos personalizados muy chulos creados por Alvi conllevó  la pérdida de dichos modos de visión, estaría fantástico si se pudiera volver a implementar a nuestros nuevos cascos.

**Comment by MultiTheFranky** [comment]
Applied
