### ISSUE TITLE
[Sugerencia] Cambiar apariencia de los camiones de transporte de Rancor

### ISSUE THREAD

**Issue by zarzanduil** [MultiTheFranky/41st-StarWars-Mod#6]
**Is your feature request related to a problem? Please describe.**
Actualmente los cambiones que utiliza Rancor para el transporte de infanteria tiene los colores y escudo del CIS.

**Describe the solution you'd like**
Que los colores y el logo corresponda con los de la republica

**Additional context**
![Captura de pantalla (6)](https://user-images.githubusercontent.com/45758857/57988093-4c8e9900-7a8a-11e9-8394-832c5884ddde.png)

**Comment by MultiTheFranky** [comment]
Buenas @zarzanduil necesito el class name del vehículo que se puede extraer sacándolo en el editor y haciendo botón derecho sobre él > registro/log > algo de classname. También necesito algo de apoyo visual para saber cual sería el color y el logo correspondiente. Un saludo :)

**Comment by zarzanduil** [comment]
### Desde el config viewer:
**Path:**
configfile >> "CfgVehicles" >> "CIS_Tempest"
**Parents:**["O_Truck_03_covered_F","Truck_03_base_F","Truck_F","car_f","Car","LandVehicle","Land","AllVehicles","All"]
### Ayuda visual
![20190520173027_1](https://user-images.githubusercontent.com/45758857/58033614-1520fa80-7b25-11e9-96bf-55830f7ef122.jpg)
Esos son los colores que por ejemplo utiliza el coche de HQ

**Comment by elruffus** [comment]
Nos ponemos con ello, en cuanto tengamos previsión os decimos.

**Comment by MultiTheFranky** [comment]
Applied
